#!/usr/bin/env python3
"""Paper-level visualization for q1."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "src"
SCRIPT_DIR = Path(__file__).resolve().parent
for path in [SRC, SCRIPT_DIR]:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from modeling_common.artifacts import save_figure_bundle  # noqa: E402


def _load_profiles(root: Path) -> pd.DataFrame:
    data_dir = root / "artifacts" / "q1" / "data"
    frames = [
        pd.read_csv(data_dir / "constant_speed_profile.csv"),
        pd.read_csv(data_dir / "constant_mach_profile.csv"),
    ]
    return pd.concat(frames, ignore_index=True)


def _line_figure(data: pd.DataFrame, *, x: str, y: str, title: str, ylabel: str) -> plt.Figure:
    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    for strategy, frame in data.groupby("strategy", sort=False):
        ax.plot(frame[x], frame[y], label=strategy.replace("_", " "))
    ax.set_title(title)
    ax.set_xlabel(x)
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.3)
    ax.legend()
    return fig


def create_figures(root: Path | None = None) -> list[dict[str, Path]]:
    root = root or ROOT
    qdir = root / "questions" / "q1"
    profiles = _load_profiles(root)
    comparison = pd.read_csv(root / "artifacts" / "q1" / "data" / "strategy_comparison.csv")
    outputs: list[dict[str, Path]] = []

    specs = [
        ("height_time", "time_s", "height_m", "Height vs time", "height (m)"),
        ("mass_time", "time_s", "mass_kg", "Mass vs time", "mass (kg)"),
        ("climb_rate_time", "time_s", "climb_rate_mps", "Climb rate vs time", "climb rate (m/s)"),
        ("height_distance", "distance_m", "height_m", "Height vs ground distance", "height (m)"),
    ]
    for stem, x_col, y_col, title, ylabel in specs:
        figure_data = profiles[["strategy", x_col, y_col]].copy()
        fig = _line_figure(figure_data, x=x_col, y=y_col, title=title, ylabel=ylabel)
        outputs.append(
            save_figure_bundle(
                fig=fig,
                data=figure_data,
                stem=stem,
                question_dir=qdir,
                title=title,
                source_script="questions/q1/scripts/visualize.py",
                notes="Source profiles generated by questions/q1/scripts/pipeline.py",
            )
        )
        plt.close(fig)

    metrics = comparison[
        ["strategy", "final_time_s", "final_distance_m", "final_height_m", "mean_climb_rate_mps"]
    ].copy()
    long_metrics = metrics.melt(id_vars="strategy", var_name="metric", value_name="value")
    fig, axes = plt.subplots(2, 2, figsize=(8.0, 6.0))
    for ax, metric in zip(axes.ravel(), metrics.columns[1:], strict=True):
        subset = long_metrics[long_metrics["metric"] == metric]
        ax.bar(subset["strategy"].str.replace("_", " "), subset["value"])
        ax.set_title(metric)
        ax.tick_params(axis="x", rotation=15)
        ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    outputs.append(
        save_figure_bundle(
            fig=fig,
            data=long_metrics,
            stem="strategy_metrics",
            question_dir=qdir,
            title="Strategy metric comparison",
            source_script="questions/q1/scripts/visualize.py",
            notes="Metric comparison from strategy_comparison.csv",
        )
    )
    plt.close(fig)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description="Create q1 figures")
    parser.parse_args()
    create_figures(ROOT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
